
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 05 02:37:37 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int printi = 37;
  public static final int igual2 = 12;
  public static final int printf = 35;
  public static final int igual1 = 2;
  public static final int alla = 8;
  public static final int rvoid = 26;
  public static final int dividir = 21;
  public static final int coma = 3;
  public static final int rgoto = 39;
  public static final int rstack = 32;
  public static final int potenciar = 23;
  public static final int numero = 46;
  public static final int rif = 38;
  public static final int menos = 19;
  public static final int menor = 15;
  public static final int EOF = 0;
  public static final int aumento = 24;
  public static final int dosp = 4;
  public static final int mas = 18;
  public static final int rint = 27;
  public static final int error = 1;
  public static final int rchar = 30;
  public static final int rstring = 29;
  public static final int tstring = 41;
  public static final int mayor = 14;
  public static final int menorigual = 17;
  public static final int por = 20;
  public static final int rfalse = 44;
  public static final int id = 45;
  public static final int ccor = 11;
  public static final int fin = 5;
  public static final int mayorigual = 16;
  public static final int diferente = 13;
  public static final int rbool = 31;
  public static final int decremento = 25;
  public static final int cpar = 7;
  public static final int rcall = 40;
  public static final int modular = 22;
  public static final int clla = 9;
  public static final int rmain = 34;
  public static final int rdouble = 28;
  public static final int prints = 36;
  public static final int acor = 10;
  public static final int rheap = 33;
  public static final int rtrue = 43;
  public static final int tchar = 42;
  public static final int apar = 6;
}

