
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 02 03:39:42 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int potenciar = 6;
  public static final int apar = 9;
  public static final int aumento = 7;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int numero = 12;
  public static final int decremento = 8;
  public static final int error = 1;
  public static final int por = 4;
  public static final int cpar = 10;
  public static final int punto_coma = 11;
  public static final int mas = 2;
  public static final int dividir = 5;
}

