
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 16 23:41:51 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int rfalse = 17;
  public static final int desplegar = 6;
  public static final int numero = 15;
  public static final int imprimir = 5;
  public static final int cpar = 9;
  public static final int por = 12;
  public static final int rtrue = 16;
  public static final int aumento = 13;
  public static final int operar = 4;
  public static final int iniciar = 2;
  public static final int menos = 11;
  public static final int EOF = 0;
  public static final int decremento = 14;
  public static final int error = 1;
  public static final int terminar = 3;
  public static final int mas = 10;
  public static final int punto_coma = 7;
  public static final int apar = 8;
}

